# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpecialTopicProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpecialTopicProject

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'ApiAI'

  target 'SpecialTopicProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpecialTopicProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
